parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Presentation/'
            - '../src/Kernel.php'

    routing.loader.attribute.post:
        class: App\Shared\Presentation\Routing\OpenAPIRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\Routing\Attribute\Post']]
        tags:
            - { name: 'routing.loader', priority: -10 }

    routing.loader.attribute.get:
        class: App\Shared\Presentation\Routing\OpenAPIRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\Routing\Attribute\Get']]
        tags:
            - { name: 'routing.loader', priority: -10 }

    routing.loader.attribute.put:
        class: App\Shared\Presentation\Routing\OpenAPIRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\Routing\Attribute\Put']]
        tags:
            - { name: 'routing.loader', priority: -10 }

    routing.loader.attribute.patch:
        class: App\Shared\Presentation\Routing\OpenAPIRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\Routing\Attribute\Patch']]
        tags:
            - { name: 'routing.loader', priority: -10 }

    routing.loader.attribute.delete:
        class: App\Shared\Presentation\Routing\OpenAPIRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\Routing\Attribute\Delete']]
        tags:
            - { name: 'routing.loader', priority: -10 }
