parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Shared\Presentation\Publisher\FeaturePublisher:
            tags: ['api.feature_publisher']

        App\Shared\Presentation\Provider\GroupsProvider:
            tags: ['api.groups_provider']

        App\Shared\Presentation\OpenApi\Analyser\AttributeFactory:
            tags: ['api.attribute_factory']

        OpenApi\Analysers\AnnotationFactoryInterface:
            tags: ['api.annotation_factory']

        OpenApi\Processors\ProcessorInterface:
            tags: ['api.processor']

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    routing.loader.attribute.post:
        class: App\Shared\Presentation\OpenApi\Routing\Loader\OpenApiRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\OpenApi\Routing\Attribute\Post']]
        tags:
            - { name: 'routing.loader', priority: -10 }

    routing.loader.attribute.get:
        class: App\Shared\Presentation\OpenApi\Routing\Loader\OpenApiRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\OpenApi\Routing\Attribute\Get']]
        tags:
            - { name: 'routing.loader', priority: -10 }

    routing.loader.attribute.put:
        class: App\Shared\Presentation\OpenApi\Routing\Loader\OpenApiRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\OpenApi\Routing\Attribute\Put']]
        tags:
            - { name: 'routing.loader', priority: -10 }

    routing.loader.attribute.patch:
        class: App\Shared\Presentation\OpenApi\Routing\Loader\OpenApiRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\OpenApi\Routing\Attribute\Patch']]
        tags:
            - { name: 'routing.loader', priority: -10 }

    routing.loader.attribute.delete:
        class: App\Shared\Presentation\OpenApi\Routing\Loader\OpenApiRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\OpenApi\Routing\Attribute\Delete']]
        tags:
            - { name: 'routing.loader', priority: -10 }
