parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Shared\Presentation\OpenApi\Processor\Publisher\FeaturePublisher:
            tags: ['api.endpoint_publisher']

        App\Shared\Presentation\Provider\GroupsProvider:
            tags: ['api.groups_provider']

    App\:
        resource: '../src/'
        exclude:
            - '../src/Presentation/'
            - '../src/Kernel.php'

    routing.loader.attribute.post:
        class: App\Shared\Presentation\OpenApi\Routing\Loader\OpenApiRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\OpenApi\Routing\Attribute\Post']]
        tags:
            - { name: 'routing.loader', priority: -10 }

    routing.loader.attribute.get:
        class: App\Shared\Presentation\OpenApi\Routing\Loader\OpenApiRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\OpenApi\Routing\Attribute\Get']]
        tags:
            - { name: 'routing.loader', priority: -10 }

    routing.loader.attribute.put:
        class: App\Shared\Presentation\OpenApi\Routing\Loader\OpenApiRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\OpenApi\Routing\Attribute\Put']]
        tags:
            - { name: 'routing.loader', priority: -10 }

    routing.loader.attribute.patch:
        class: App\Shared\Presentation\OpenApi\Routing\Loader\OpenApiRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\OpenApi\Routing\Attribute\Patch']]
        tags:
            - { name: 'routing.loader', priority: -10 }

    routing.loader.attribute.delete:
        class: App\Shared\Presentation\OpenApi\Routing\Loader\OpenApiRouteControllerLoader
        arguments:
            - '%kernel.environment%'
        calls:
            - [setRouteAnnotationClass, ['App\Shared\Presentation\OpenApi\Routing\Attribute\Delete']]
        tags:
            - { name: 'routing.loader', priority: -10 }
